import '../entities/book.entity.dart';

List<Book> bookListMock = [
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart",
    year: 2022,
  ),
  Book(
    author: "Doidin La",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 2",
    year: 2022,
  ),
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 3",
    year: 2022,
  ),
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 2",
    year: 2022,
  ),
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 2",
    year: 2022,
  ),
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 2",
    year: 2022,
  ),
  Book(
    author: "Renan Volpe",
    available: true,
    cover: "https://www.jurua.com.br/images/prod/b/20/20104.jpg?ts=20201218",
    id: 11,
    idStore: 125,
    rating: 1,
    synopsis: "...",
    title: "O guia de Dart 2",
    year: 2022,
  )
];
